# Generated by Django 3.0.2 on 2020-01-06 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mp4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_path', models.FileField(max_length=500, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('file_hash', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Видеоролик',
                'verbose_name_plural': 'Видеоролики',
            },
        ),
    ]
