# Generated by Django 3.0.2 on 2020-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='desc',
            field=models.CharField(max_length=100, verbose_name='описание'),
        ),
    ]
