# Generated by Django 3.0.2 on 2020-01-06 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0002_auto_20200106_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4'])], verbose_name='загрузить файл!'),
        ),
    ]
