# Generated by Django 3.0.2 on 2020-01-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0003_auto_20200106_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='file_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
