# Generated by Django 3.0.2 on 2020-01-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0004_auto_20200107_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
