# Generated by Django 3.0.2 on 2020-01-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0005_auto_20200107_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp4',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='archives/%Y/%m%/d/', verbose_name='загрузить файл!'),
        ),
    ]
