# Generated by Django 3.0.2 on 2020-01-07 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mp4_work', '0006_auto_20200107_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp4',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mp4',
            name='file_path',
            field=models.FileField(max_length=500, upload_to='archives/%Y/%m/%d/', verbose_name='загрузить файл!'),
        ),
    ]
